repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Ventoy
repo_name: 2023.2-Ventoy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

site_name: Ventoy
nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
      - Apresentação 4: apresentacao/apresentacao4.md
      - Apresentação 5: apresentacao/apresentacao5.md
      - Apresentação 6: apresentacao/apresentacao6.md
      - Apresentação 7: apresentacao/apresentacao7.md
      - Apresentação Final: apresentacao/Entrega--Final.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/Ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Políticas: planejamento/políticas.md
      - Heatmap: planejamento/Heatmap.md
      - Processo design: planejamento/processo_de_design.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
  - Análise de Requisitos I:
    - Aspectos Éticos: AnaliseDeRequisitos/aspectosEticos.md
    - Perfil de Usuário: elicitacao/PerfilUsuario.md
    - Persona: elicitacao/Persona.md
    - Cenários: AnaliseDeRequisitos/cenarios.md
    - Elicitação:
        - Entrevista: elicitacao/elicitacao de requisitos/entrevista.md
        - Brainstorming: elicitacao/elicitacao de requisitos/Brainstorming.md
        - Introspecção: elicitacao/elicitacao de requisitos/introspeccao.md
        - Grupo de foco: elicitacao/elicitacao de requisitos/GrupoDeFoco.md
    - Análise de Tarefas: 
        - Análise Hierarquica de Tarefas - HTA: AnaliseDeRequisitos/analisedetarefas/analiseHierarquicaDeTarefas.md
        - ConcurTaskTrees - CTT: AnaliseDeRequisitos/analisedetarefas/ConcurTaskTrees.md
  - Análise de requisitos II:
        - Princípios Gerais: AnaliseDeRequisitos/principiosGerais.md
        - Características Gerais: AnaliseDeRequisitos/caracteristicasGerais.md
        - Metas de Usabilidade: AnaliseDeRequisitos/metasUsabilidade.md
        - Guia de Estilo: AnaliseDeRequisitos/guia-de-estilo.md       
  - Design, Avaliação e Desenvolvimento: 
    - Nível 1:
      - Storyboard:
          - Planejamento da Avaliação do Storyboard: DAD/nivel1/storyboard/planejamentoStoryboard.md
          - Planejamento do Relato dos Resultados: DAD/nivel1/storyboard/resultadoStory.md
          - Relato dos Resultados do Storyboard: DAD/nivel1/storyboard/relatoDosResultados.md
          - Storyboards: DAD/nivel1/storyboard/storyboards.md
      - Análise de Tarefas:
          - Planejamento da Avaliação da Análise de Tarefas: DAD/nivel1/AnaliseTarefas/planejamento.md
          - Planejamento do Relato dos Resultados da Avaliação: DAD/nivel1/analiseDeTarefas/planejamentoResultadosAnaliseTarefas.md
          - Relato dos Resultados da Avaliação: DAD/nivel1/AnaliseTarefas/resultado.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação do protótipo de papel: DAD/nivel2/prototipoDePapel/planejamento_avaliacao.md
        - Planejamento do Relato dos resultados do protótipo de papel: DAD/nivel2/prototipoDePapel/planejamento_relato.md
        - Protótipos de papel: DAD/nivel2/prototipoDePapel/Prototipos.md
        - Relato dos Resultados:
          - Criar post no fórum: DAD/nivel2/prototipoDePapel/resultado_post-forum.md
          - Acessar a aba de plugin: DAD/nivel2/prototipoDePapel/RelatoPlugin.md
          - Acessar a página de FAQ para consultar dúvida: DAD/nivel2/prototipoDePapel/RelatoFAQ.md
          - Acessar a página de Testes de ISO para verificar os testes: DAD/nivel2/prototipoDePapel/RelatoTesteISO.md
          - Realizar doação: DAD/nivel3/relato-dos-resultados-prototipo-de-papel/donation.md
          - Acessar a página de Compartilhamento de Experiências para consultar relatos: DAD/nivel2/prototipoDePapel/RelatoEXP.md
          - Iniciar o uso do Ventoy: DAD/nivel2/prototipoDePapel/resultado_comecar-usar-ventoy.md
    - Nível 3:
      - Protótipo de alta fidelidade:
        - Planejamento da Avaliação do protótipo de alta fidelidade: DAD/nivel2/prototipoAltaFidelidade/PlanejamentoAvaliacaoPAF.md
        - Planejamento do Relato dos resultados do protótipo de alta fidelidade: DAD/nivel2/prototipoAltaFidelidade/PlanejamentoRelatoPrototipoAltaFidelidade.md
        - Relatos dos Prótotipos de alta fidelidade:
          - Relato Plugin: DAD/nivel2/prototipoAltaFidelidade/RelatoPlugin.md
          - Relato Donation: DAD/nivel3/relato-alta-fidelidade/donation.md
          - Relato Iniciar o uso do Ventoy: DAD/nivel3/relato-alta-fidelidade/iniciar-uso-do-ventoy.md
          - Relato Teste de Iso: DAD/nivel3/relato-alta-fidelidade/TesteDeISO.md
          - Relato Realizar Postagem no Fórum: DAD/nivel3/relato-alta-fidelidade/forum.md
          - Relato Realizar Consulta no FAQ: DAD/nivel3/relato-dos-resultados-prototipo-de-papel/FAQ.md
  - Verificação:
    - Grupo 03:
          - Planejamento da verificação: verificacao/planejamendoDaVerificacao.md
          - Planejamento:
            - Metodologia: verificacao/Metodologia.md
            - Heatmap: verificacao/Heatmap.md
            - Sites Avaliados: verificacao/SitesAvaliados.md
            - Site Selecionado: verificacao/SiteSelecionado.md
            - Ferramentas: verificacao/planejamento/ferramentas.md
            - Cronograma: verificacao/planejamento/cronograma.md
            - Padronização do Projeto: verificacao/padronizacaoProjeto.md
            - Processos de design: verificacao-nossa-grupo02/planejamento/verificacao-processo-design.md
          - Análise de requisitos I:
            - Aspectos Éticos: verificacao/aspectos_eticos.md
            - Perfil de usuário: verificacao/analiseRequisito/perfilUsuario.md
            - Personas: verificacao/analiseRequisito/personas.md
            - Cenários: verificacao/cenarios.md
            - Elicitação:
              - Introspecção: verificacao/analiseRequisito/introspeccao.md
              - Observação: verificacao/Observacao.md
            - Análise de Tarefas:
              - Análise Hierárquica de Tarefas: verificacao/analiseHierarquicaDeTarefas.md
              - Árvore de Tarefas Concorrentes: verificacao/CTT.md
          - Análise de requisitos II:
            - Princípios Gerais: verificacao/principiosGerais.md
            - Caracteristicas Gerais: verificacao/CaracteristicasDaPlataforma.md
            - Caracteristicas da Plataforma: verificacao/CaracteristicasDaPlataforma.md
            - Metas de usabilidade: verificacao/AnaliseRequisitos/metasUsabilidade.md
            - Guia de estilo: verificacao/GuiaDeEstilo.md
          - Design, avaliação e desenvolvimento:
            - Análise de Tarefas:
              - Planejamento da Avaliação da Análise de Tarefas: verificacao/DAD/nivel01/analiseDeTarefas/planejamento_avalicao_analise_de_tarefas.md
              - Planejamento do Relato dos Resultados da Avaliação: verificacao/DAD/nivel01/analiseDeTarefas/planRelatoResultados.md
              - Relato dos Resultados: verificacao/DAD/nivel01/analiseDeTarefas/relatoResultados.md
            - Storyboard:
              - Planejamento da Avaliação do Storyboard: verificacao/DAD/nivel01/storyboard/planejamento_avaliacao_storyboar.md
              - Planejamento do Relato dos Resultados: verificacao/DAD/nivel01/storyboard/planejamento_relato_resultados_storyboard.md
              - Relato dos Resultados do Storyboard: verificacao/DAD/nivel01/storyboard/relato_resultados.md
              - Storyboards: verificacao/DAD/nivel01/storyboard/storyboards.md
            - Protótipo de papel:
              - Planejamento da Avaliação do protótipo de papel: verificacao/plan_avaliacao.md
              - Planejamento do Relato dos resultados do protótipo de papel: verificacao/plan_relato.md


    - Grupo 02:
      - Planejamento: 
        - Cronograma: verificacao-nossa-grupo02/planejamento/cronograma.md
        - Ferramentas: verificacao-nossa-grupo02/planejamento/ferramentas.md
        - Metodologia: verificacao-nossa-grupo02/planejamento/metodologia.md
        - Políticas: verificacao-nossa-grupo02/planejamento/politicas.md
        - Heatmap: verificacao-nossa-grupo02/planejamento/HeatMap.md
        - Processo design: verificacao-nossa-grupo02/planejamento/verificacao-processo-design.md
        - Sites avaliados: verificacao-nossa-grupo02/planejamento/SitesAvaliados.md
        - Site escolhido: verificacao-nossa-grupo02/planejamento/site-escolhido.md
      - Análise de Requisitos I:
        - Aspectos Éticos: verificacao-nossa-grupo02/analise-req-1/aspectosEticos.md
        - Perfil de Usuário(adicionar): verificacao-nossa-grupo02/ventoy.md
        - Persona: verificacao-nossa-grupo02/analise-req-1/verificacao-personas.mdd
        - Cenários: verificacao-nossa-grupo02/analise-req-1/cenarios.md
        - Elicitação:
          - Entrevistas:
            - Lista de verificação: verificacao-nossa-grupo02/entrevista/checklist.md
            - Inspeção: verificacao-nossa-grupo02/entrevista/inspecao.md
          - Brainstorming: verificacao-nossa-grupo02/analise-req-1/Brainstorming.md
          - Introspecção: verificacao-nossa-grupo02/analise-req-1/introspeccao.md
          - Grupo de foco: verificacao-nossa-grupo02/analise-req-1/GrupoFoco.md
        - Análise de Tarefas: 
          - Análise Hierárquica de Tarefas - HTA*: verificacao-nossa-grupo02/ventoy.md
          - ConcurTaskTrees - CTT: verificacao-nossa-grupo02/analise-req-1/verificacao-CTT.md
      - Análise de requisitos II: 
        - Princípios Gerais: verificacao-nossa-grupo02/analise-req-2/Principios-Gerais.md
        - Características Gerais: verificacao-nossa-grupo02/ventoy.md
        - Metas de Usabilidade: verificacao-nossa-grupo02/ventoy.md
        - Guia de Estilo: verificacao-nossa-grupo02/analise-req-2/Principios-Gerais.md
      - Design, Avaliação e Desenvolvimento:
        - Nível 1:
          - Storyboard:
            - Planejamento da Avaliação do Storyboard: verificacao-nossa-grupo02/D.A.D/storyboard/planejamento-da-avaliacao.md
            - Planejamento do Relato dos Resultados: verificacao-nossa-grupo02/D.A.D/storyboard/planejamento-relato-dos-resultados.md
            - Relato dos Resultados do Storyboard(add): verificacao-nossa-grupo02/D.A.D/storyboard/Verificação Storyboards.md
            - Storyboards: verificacao-nossa-grupo02/D.A.D/storyboard/Verificação Storyboards.md
          - Análise de Tarefas:
            - Planejamento da Avaliação da Análise de Tarefas: verificacao-nossa-grupo02/D.A.D/analise-de-tarefas/planejamentoAvaliação.md
            - Planejamento do Relato dos Resultados da Avaliação: verificacao-nossa-grupo02/D.A.D/analise-de-tarefas/planejamento-relato-dos-resultados.md
            - Relato dos Resultados da Avaliação: verificacao-nossa-grupo02/D.A.D/analise-de-tarefas/RelatoDosResultados.md
        - Nível 2:
          - Protótipo de Papel: 
            - Planejamento da Avaliação do protótipo de papel: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/planejamento-da-avaliacao.md
            - Planejamento do Relato dos resultados do protótipo de papel: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/planejamento-relato-resultado-pp.md
            - Protótipos de papel: verificacao-nossa-grupo02/ventoy.md
            - Relato dos Resultados: 
              - Criar post no fórum: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/resultados/criar-post-forum.md
              - Acessar a aba de plugin: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/resultados/acessar-aba-plugin.md
              - Acessar a página de FAQ para consultar dúvida*: verificacao-nossa-grupo02/ventoy.md
              - Acessar a página de Testes de ISO para verificar os testes: verificacao-nossa-grupo02/resultados.md
              - Realizar doação*: verificacao-nossa-grupo02/ventoy.md
              - Acessar a página de Compartilhamento de Experiências para consultar relatos: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/resultados/Compartilhamento.md
              - Iniciar Uso do Ventoy: verificacao-nossa-grupo02/D.A.D/prototipos-de-papel/resultados/iniciar-ventoy.md
        - Nível 3:
          - Protótipo de alta fidelidade:
            - Planejamento da Avaliação do protótipo de alta fidelidade: verificacao-nossa-grupo02/ventoy.md
            - Planejamento do Relato dos resultados do protótipo de alta fidelidade: verificacao-nossa-grupo02/ventoy.md
            - Relatos dos Prótotipos de alta fidelidade: 
              - Relato Plugin: verificacao-nossa-grupo02/D.A.D/prototipo-alta-fidelidade/relatos/acessar-aba-plugin.md
              - Relato Donation: verificacao-nossa-grupo02/D.A.D/prototipo-alta-fidelidade/relatos/realizarDoação
              - Relato Iniciar o uso do Ventoy: verificacao-nossa-grupo02/D.A.D/prototipo-alta-fidelidade/relatos/IniciarUsoDoVentoy.md
              - Relato Teste de ISO: verificacao-nossa-grupo02/
              - Relato Realizar Postagem no Fórum: verificacao-nossa-grupo02/prototipo-alta-fidelidade/relatos/criar-post-forum
              - Página de FAQ: verificacao-nossa-grupo02/D.A.D/prototipo-alta-fidelidade/relatos/resultados/faq.md
  - Apresentação Final:
      - Site Selecionado: entrega-final/site_escolhido.md
      - Ciclo de Vida Utilizado: entrega-final/CicloDeVida.md
      - Cronograma Planejado e Executado: entrega-final/Cronograma.md
      - Execução do Projeto: entrega-final/execucaoCicloDeVida.md
      - Resultados Alcançados: entrega-final/resultados-alcan.md
      - Síntese das Ferramentas: entrega-final/ferramentas-utilizadas.md
      - Síntese das Técnicas: entrega-final/sintese-metodos.md
      - Síntese dos Artefatos: entrega-final/sintese-artefatos.md
      - Síntese das Entrevistas: entrega-final/tabela-entrevistados.md
      - Síntese das Verificações: entrega-final/sintese-verificacao.md
      - Síntese das Apresentações: entrega-final/sintese-video-apresentações.md
      - Considerações Finais: entrega-final/consideracoesFinais.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro

  language: pt-BR
  favicon: assets/icon.PNG
  logo: assets/icon.PNG

