repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Ventoy
repo_name: 2023.2-Ventoy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

site_name: Ventoy
nav:
  - Sobre o projeto: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
  - Atas:
      - Ata 2: atas/ata2.md
  - Planejamento:
      - Cronograma planejado: planejamento/cronograma/planejado.md
      - Cronograma executado: planejamento/cronograma/executado.md
      - Ferramentas: planejamento/ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Heatmap: planejamento/Heatmap.md
      - Planejamento da avaliação: planejamento/Planejamento-da-avaliacao.md
      - Processo design: planejamento/processo_de_design.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: assets/icon.PNG
  logo: assets/icon.PNG

