repo_url: https://github.com/Interacao-Humano-Computador/2023.2-Ventoy
repo_name: 2023.2-Ventoy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

site_name: Ventoy
nav:
  - Home: index.md
  - Apresentações:
      - Apresentação 1: apresentacao/apresentacao1.md
      - Apresentação 2: apresentacao/apresentacao2.md
      - Apresentação 3: apresentacao/apresentacao3.md
  - Atas:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
      - Ata 4: atas/ata4.md
      - Ata 5: atas/ata5.md
  - Planejamento:
      - Cronograma: planejamento/cronograma.md
      - Ferramentas: planejamento/Ferramentas.md
      - Metodologia: planejamento/metodologia.md
      - Políticas: planejamento/políticas.md
      - Heatmap: planejamento/Heatmap.md
      - Processo design: planejamento/processo_de_design.md
      - Sites avaliados: planejamento/sites-avaliados.md
      - Site escolhido: planejamento/site-escolhido.md
  - Análise de Requisitos I:
    - Aspectos Éticos: AnaliseDeRequisitos/aspectosEticos.md
    - Perfil de Usuário: elicitacao/PerfilUsuario.md
    - Persona: elicitacao/Persona.md
    - Cenários: AnaliseDeRequisitos/cenarios.md
    - Elicitação:
        - Entrevista: elicitacao/elicitacao de requisitos/entrevista.md
        - Brainstorming: elicitacao/elicitacao de requisitos/Brainstorming.md
        - Introspecção: elicitacao/elicitacao de requisitos/introspeccao.md
        - Grupo de foco: elicitacao/elicitacao de requisitos/GrupoDeFoco.md
    - Análise de Tarefas: 
        - Análise Hierarquica de Tarefas - HTA: AnaliseDeRequisitos/analisedetarefas/analiseHierarquicaDeTarefas.md
        - ConcurTaskTrees - CTT: AnaliseDeRequisitos/analisedetarefas/ConcurTaskTrees.md
  - Análise de requisitos II:
        - Princípios Gerais: AnaliseDeRequisitos/principiosGerais.md
        - Características Gerais: AnaliseDeRequisitos\caracteristicasGerais.md
        - Metas de Usabilidade: AnaliseDeRequisitos\metasUsabilidade.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
    - Storyboard:
        - Storyboard: DAD/nivel1/storyboard/storyboards.md
        - Planejamento da Avaliação: Design,AvaliçãoeDesenvolvimento\planejamentoStoryboard.md
        
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/circle-half-full
        name: Mudar para o modo claro

  language: pt-BR
  favicon: assets/icon.PNG
  logo: assets/icon.PNG
